nette/docs

- tester/cs/homepage.texy
- tester/en/homepage.texy
Mergnu to, pokud nebudou připomínky.
> Tester: own php.ini chapter

- cs/@docmenu.texy
- cs/debugger-extensions.texy
- cs/debugging.texy
- en/@docmenu.texy
- en/debugger-extensions.texy
- en/debugging.texy
Added tutorial on debugger bar extensions, which is merely an update and translation of [this forum thread](http://forum.nette.org/cs/7221-jak-psat-rozsireni-pro-debugger-bar).
Feedback would be appreciated.
> debugger-bar-extensions: added

- cs/testing.texy
- en/testing.texy
ref https://github.com/nette/tester/issues/188
> Tester: added mention about HHVM support

- cs/access-control.texy
- en/access-control.texy
> AccessControl: removed container reference

- cs/forms.texy
- en/forms.texy
ref https://github.com/nette/web-content/issues/180
- Intro revamp
- fixed rendering section
- added 2.1 features
- fixed "Validace celého formuláře" section
- added section about independent usage of Nette\Forms
When this is approved, I will fix the EN version too.
> Forms: update for 2015

- cs/configuring.texy
- cs/sessions.texy
- en/configuring.texy
- en/sessions.texy
EN version will be added after this is approved :)
> Sessions: fixed container usage and configuration

- cs/caching.texy
- en/caching.texy
> Caching: container usege removed + small fixes

- cs/mailing.texy
- en/mailing.texy
I have removed caution about sending passwords via e-mail, added checklist into perex, changed structure and mentioned link building when using templates.
Should I leave the `UIMacros::install()` tutorial or is not appropriate?
Note: after the changes are approved, I will fix the EN version aswell.
> Mailing: mentioned link building + updates

- pla/cs/best-practise-formulare-jako-komponenty.texy
Bylo by třeba kontrolovat, pokud by šlo o `onSubmit`. Odstranil bych to tedy z návodu, aby to některé nemátlo.
> Validitu v `onSuccess` není třeba kontrolovat.

- en/composer.texy
* Replaced the czech 'nebo' with the english 'or' in `en/composer.texy`
> update: Replaced 'nebo' with 'or' in composer.texy

- cs/default-macros.texy
- en/default-macros.texy
> added macro {php …} as replacement for {? …}

- en/debugging.texy
Change in 2.0 documentation of #280.
> Debugging: fixed translation of key (2.0)

- en/debugging.texy
Change in 2.1 documentation of #280.
> Debugging: fixed translation of key (2.1)

- en/debugging.texy
Change in 2.2 documentation of #280.
> Debugging: fixed translation of key (2.2)

- en/debugging.texy
Change in 2.3 documentation of #280.
> Debugging: fixed translation of key (2.3)

- cs/ajax.texy
- en/ajax.texy
> Ajax: Fix GitHub upper-case letters

- cs/quickstart/home-page.texy
> Quickstart: Home-page - fix broken link to macros

- en/php-language-enhancements.texy
> Update php-language-enhancements.texy (typo)

- cs/default-filters.texy
- en/default-filters.texy
Oprava chyb + pull request do správné větve
> Update bad name escapeurl in v2.3

- cs/default-helpers.texy
I send changes to bad tree. (Poslal jsme změny do špatné větve). Commit must be in version 2.3. I send new pull request.
> Revert "Update default-helpers.texy"

- en/database-selection.texy
> fixed misspelling

- cs/code-checker.texy
- cs/homepage.texy
- cs/testing.texy
- en/code-checker.texy
- en/homepage.texy
- en/testing-with-travis.texy
- en/testing.texy
- added links on code-checker github
- added new option for code-checker (-i <mask>)
- added link to composer in english documentation
> A little of content enhancement.

- cs/access-control.texy
- en/access-control.texy
> Access control: Multiple authentication segments

- cs/templating.texy
- en/templating.texy
> templating: recomended filtr registration

- tester/cs/homepage.texy
- tester/en/homepage.texy
> Tester: update for 1.7.0

- cs/routing.texy
- en/routing.texy
From https://github.com/nette/application/pull/129
> added second level domain to nette/routing

- www/en/homepage.texy
Do you want users to learn Nette FW for a very short time and then forget it? Or you want them to learn it fast and simply? :-)
> Just a typo changes full meaning

- cs/database.texy
- en/database.texy
Hi,
I have created a fix of documentation based on this https://github.com/nette/database/issues/130#issuecomment-215217716
Thank you.
> Fix to Connection default lazy behaviour

- cs/migration-2-3.texy
- en/migration-2-3.texy
for more info see nette/http#90 issue
> migration 2.3: DI - BC break for dynamically service replacing

- cs/forms.texy
- en/forms.texy
Maybe it needs tune texts a little bit.
> Forms: readonly mode of input.

- www/en/homepage.texy
for better comprehension and to better convey the intended meaning
> Improve English homepage texts

- en/forms.texy
Translate text to english and fix typo I noticed in form documentation
> Translate czech text to english

- cs/forms.texy
- en/forms.texy
Rules are unified and grouped as in Form.php file.
> Unified form rules and added missing few

- cs/forms.texy
- cs/getting-started.texy
- en/components.texy
- en/forms.texy
- en/getting-started.texy
- en/quickstart/home-page.texy
Repaired all bad links in documentation 2.3
Source of bad links https://doc.nette.org/special/broken-links?lang=cs
> Repaired wrong links in doc-2.3

- cs/forms.texy
- cs/getting-started.texy
- en/components.texy
- en/forms.texy
- en/getting-started.texy
- en/quickstart/home-page.texy
Repaired all bad links in documentation 2.4
Source of bad links https://doc.nette.org/special/broken-links?lang=cs
> Repaired wrong links in doc-2.4

- cs/database-selection.texy
- en/database-selection.texy
This is documentation for nette/database#111
> added documentation for new whereOr() method

- cs/di-usage.texy
Opraveno aby fungovalo inteligentní napovídání v phpstormu, viz: https://youtrack.jetbrains.com/issue/WI-29714
> Opraveno aby fungovalo inteligentní napovídání v phpstormu, viz: https://youtrack.jetbrains.com/issue/WI-29714

- cs/presenters.texy
- en/presenters.texy
musel jsem prepsat nadpisy, potrebuju h4 :P
> presenter config

- cs/images.texy
Přidána poznámka o ukládání změněných obrázků a odkaz na fórum, kde se to ta problematika řeší.
> Přidána poznámka o ukládání změněných obrázků.

- cs/components.texy
> Generated factories with param and service

- en/routing.texy
The current state of modularity section is bad – it uses static method and a $container. But I don't know how to write an elegant modern alternative which is not too complex.
The code is an early draft I don't really like.
> Routing: modularity section

- cs/forms.texy
- en/quickstart/refactoring-model.texy
As requested by Chemix, this part has been translated to English.
> refactoring-model.texy english translation

- cs/routing.texy
- en/routing.texy
https://forum.nette.org/cs/26348-route-secured-nevynucuje-https-100
> routing: SECURED flag warning

- pla/en/dependent-form-select-with-ajax.texy
Changes of value in select produced duplicated and immediatelly cancelled requests.
> Fixed proper change event unbinding

- cs/html-elements.texy
- en/html-elements.texy
in Nette 2.4 method Html::add is deprecated => replaced with Html::addHtml
> Html::add is deprecated

- www/cs/homepage.texy
- www/en/homepage.texy
"Using the new features of PHP 5" doesn't sound cool nowadays, rather obsolete. 
This is more eye-catching.
> homepage: Nette 3.0 already using PHP 7.1

- cs/routing.texy
- en/routing.texy
- resolve #392
- translate HTTPS caution
> [v2.4] Routing: improvements, translations

- cs/configuring.texy
- CS: yes
- EN: no (WIP)
-----
EN translation will be followed after confirmation.
> [v2.4] Configuration: more examples and improvements

- cs/getting-started.texy
"nepopulárnější" -> "nejpopulárnější"
> Fixed a typographical error

- cs/code-checker.texy
Options now respect new version of Code checker 2.9
> Code-checker: updated description of options

- tracy/cs/homepage.texy
- tracy/en/homepage.texy
- Added references to `dump` and `bdump` shortcuts
> Tracy: Added references to dump and bdump

- en/quickstart/home-page.texy
noticed a few small typos in the docs, easy to patch :)
> fixed little typos in quickstart/home-page

- cs/homepage.texy
- en/homepage.texy
> Homepage: added link to Coding Standards

- cs/composer.texy
- en/composer.texy
It needs to be blessed by someone who has MacOS, but I think it's OK.
> Composer: suggest PHP7.1 on MacOS

- cs/quickstart/single-post.texy
- en/quickstart/single-post.texy
Changes:
- fix presenter namespace (App -> App\Presenters)
> WIP: QuickStart: changes in 2.1

- cs/quickstart.texy
Changes:
- link to propel branch 2.2
Todo:
- added info about presenter mapping [#46]
> WIP: QuickStart: updates in 2.4

- cs/homepage.texy
- cs/migration.texy
- en/homepage.texy
- en/migration.texy
It's basic concept, all kind of feedback is welcome.
> Migration: added migration page

- cs/quickstart.texy
- cs/quickstart/single-post.texy
- en/quickstart.texy
- en/quickstart/single-post.texy
Changes:
- link to Github branch/version
- added info about presenter mapping [#46]
> QuickStart - 2.4 updates

- cs/quickstart/authentication.texy
- en/quickstart/authentication.texy
> QuickStart: typo in authorization page

- www/en/terms-of-use.texy
> Terms: translated to EN

- cs/localization.texy
- en/localization.texy
> Localization: link to componette

- cs/quickstart.texy
- cs/quickstart/single-post.texy
- en/quickstart.texy
- en/quickstart/single-post.texy
Changes:
- link to propel branch 2.2 
- added info about presenter mapping [#46]
> QuickStart: updates in 2.2

- en/forms.texy
Needs more work, but let's call it a start…
> Forms: typos/grammar issues

- en/database-table.texy
- CZ: https://doc.nette.org/cs/2.4/database-table
- EN: https://doc.nette.org/en/2.4/database-table
> Database: synchronize with CZ version

- cs/database-selection.texy
- en/database-selection.texy
Please, could you check english version.
> database: add insert, update and delete

- cs/quickstart/comments.texy
- cs/quickstart/refactoring-model.texy
- cs/utils.texy
- en/quickstart/comments.texy
- en/quickstart/refactoring-model.texy
- en/utils.texy
This PR resolves some broken links in 2.4 docs.
> Bugfix: broken links [2.4]

- cs/database-explorer.texy
- cs/database-selection.texy
- cs/database.texy
- cs/quickstart/comments.texy
- cs/quickstart/refactoring-model.texy
- en/images.texy
- en/quickstart/comments.texy
This PR resolves some broken links in 2.3 docs.
> Bugfix: repair some broken links [2.3]

- latte/en/macros.texy
This PR repairs some broken links in Latte page.
> Bugfix: repair broken links [latte]

- en/configuring.texy
This PR synchronize configuring page with czech version. It resolve many issues I think. 
Most related is: #217
> Configuring: synchronize with czech version

- cs/di-extensions.texy
- en/di-extensions.texy
This PR resolves #377, only tiny typo.
> DI: use @extension prefix in example

- cs/code-checker.texy
- en/code-checker.texy
This PR adds installation note for CodeChecker and little tip to install `code checker` as project.
> CodeChecker: added installation note

- cs/homepage.texy
- cs/utils.texy
- en/homepage.texy
- en/utils.texy
I've added link to main Utils page and also I've added links to API classes on that page.
> Utils: added link to API classes, update homepage

- cs/access-control.texy
- en/access-control.texy
This PR improves access-control page.
> Security: enhancements [ref #260]

- cs/mailing.texy
- en/mailing.texy
> Mailing: drop old examples, introduce LinkGenerator

- cs/arrays.texy
This PR docs missing Arrays method.
> Arrays: added missing flatten, isList, normalize, pick, some, every, map

- cs/configuring.texy
- en/configuring.texy
I've changed example to table. Personally, I like it more. ;-)
> Configuration: better neon merging example

- cs/strings.texy
- en/strings.texy
> Strings: add substring, normalizeNewLines, firstLower methods

- cs/strings.texy
- en/strings.texy
Poprosím ještě o kontrolu metody findPrefix, u které jsem popsal parametry jen jako (array $strings).
[https://github.com/nette/utils/blob/master/src/Utils/Strings.php#L283](url)
#275
> Strings: add indexOf, after, before, findPrefix methods

- cs/configuring.texy
- en/configuring.texy
This PR resolves #219.
Please don't merge it before: https://github.com/nette/docs/pull/570
It contains only czech version, I need synchronized english version.
> Configuring: example of addDynamicParameters, addServices

- cs/json.texy
- en/json.texy
- dropped alias in head
- added usage headline
- rename presenter headline
- added composer link
> Json: dropped alias description, added usage headline, rename presenter

- cs/homepage.texy
- en/homepage.texy
- ~~prohodil jsem levy a pravy sloupecek~~
- ~~malinko jsem upravil utils~~
- ~~malinko jsem upravi DI sekci~~
-----
Pridavam par kratkych popisku ;-)
> Homepage: layout improvements

- cs/homepage.texy
| Type             | Y/N
| ---------------- | ------
| Enhancement?     | no
| Typo?            | YES
| Other?           | no
> Typo in cs/homepage.texy

- cs/forms.texy
- en/forms.texy
> Forms: add validators parameters

- cs/presenters.texy
- en/presenters.texy
For issue - https://github.com/nette/docs/issues/390
> added json & error response

- cs/filesystem.texy
- cs/utils.texy
- en/filesystem.texy
- en/utils.texy
> FileSystem: add documentation of methods

- cs/access-control.texy
- en/access-control.texy
doplnění informace, že v případě více nezávislých přihlášení se autentikátor nastavuje v checkRequirements()
> Security: kde nastavit autentikátor

- en/access-control.texy
- en/ajax.texy
- en/arrays.texy
- en/caching.texy
- en/components.texy
- en/composer.texy
- en/dependency-injection.texy
- en/di-configuration.texy
- en/forms.texy
- en/glossary.texy
- en/html-elements.texy
- en/mailing.texy
- en/passwords.texy
- en/presenters.texy
- en/quickstart/home-page.texy
- en/quickstart/refactoring-model.texy
- en/quickstart/single-post.texy
- en/robotloader.texy
- en/safestream.texy
- en/sessions.texy
- en/troubleshooting.texy
This PR fix some text typos that have been found by spellcheck #608.
> Text: typos

- cs/mailing.texy
- en/mailing.texy
For issue https://github.com/nette/docs/issues/478
> Mailing added Fallback Mailer

- readme.md
This PR resolves https://github.com/nette/docs/issues/587
> Readme 2.4: Leave a note about code-checker

- readme.md
- www/cs/writing.texy
- www/en/writing.texy
This PR resolves https://github.com/nette/docs/issues/587
> Leave a note about code-checker

- cs/safestream.texy
- en/safestream.texy
> SafeStream: note about registering

- cs/pagination.texy
- en/pagination.texy
Based on https://github.com/nette/docs/issues/242
> Pagination: tutorial, Paginator & Selection->page examples

- cs/configuring.texy
- cs/di-defaultextensions.texy
- cs/di-extensions.texy
- cs/homepage.texy
- en/configuring.texy
- en/di-defaultextensions.texy
- en/di-extensions.texy
- en/homepage.texy
This PR solves #231, #224.
-----
Zatim pracovni verze, pokud se bude libit, pridam anglickou verzi.
> DI: added example of default extensions

- tester/cs/homepage.texy
- tester/en/homepage.texy
> Tester 2.0.0

- cs/routing.texy
- en/routing.texy
This PR resolves https://github.com/nette/docs/issues/239
nejspíš bude potřeba víc úprav :)
@f3l1x @dg poprosím o review ;)
> Routing: removed deprecated container

- cs/forms.texy
- en/forms.texy
> Forms/overview: add info about reset() method closes #635 

- cs/di-configuration.texy
- en/configuring.texy
- en/di-configuration.texy
> Configuration: Setting static class propertes in config

- cs/di-extensions.texy
- en/di-extensions.texy
This PR resolves: https://github.com/nette/docs/issues/222
> DI: added info about aliases

- cs/di-configuration.texy
- en/di-configuration.texy
This PR resolves: https://github.com/nette/docs/issues/228
> DI: example of chained syntax

- tracy/cs/homepage.texy
> Tracy: added example of custom logger

- cs/di-extensions.texy
This PR solves #226 
-----
Trochu jsem upravil text u loadConfiguration, prislo mi lepsi nejdriv ukazat registraci sluzeb, ze predavani parametru. Taky jsem trochu zjednodusil ten text. 
Mrkni na to, jestli ti to prijde oukey, napisu anglickou verzi.
> DI: rewrite loadConfiguration

- cs/form-fields.texy
- en/form-fields.texy
> Missing message in addRule for ::RANGE

- cs/arrays.texy
Fixed a tiny error where in ::every example ::some was called.
> Fixed errornous static function called for ::every example

- cs/ajax.texy
Sorry, nějak jsem si nedal dohromady, že ta dokumentace má dvě jazykové verze.
> Added another alternative for client-side AJAX

- cs/configuring.texy
- en/configuring.texy
I've added all Tracy's configuration options + description.
Take a look. I could easily add an english translation if you like.
> Added Tracy configurations 

- cs/neon.texy
- en/neon.texy
I've added a few new integrations, which seems to be mising.
> Feature: update neon IDE integration

- cs/configuring.texy
- en/configuring.texy
I've added all forms constants, it's better for copy+paste and overriding. Do you agree @dg ?
> Configuring: mention all forms validation messages

- cs/ajax.texy
- en/ajax.texy
Do angličtiny bych to přeložil až po review ;)
Issue: https://github.com/nette/docs/issues/657
> Ajax: added control getParameterId

- cs/routing.texy
- en/routing.texy
> Routing: add info about caching

- cs/database-explorer.texy
- en/database-explorer.texy
- bug fix? yes
- new feature? no
- BC break? no
> Database Explorer: fix FileStorage namespace

- cs/routing.texy
- en/routing.texy
> Change wording

- cs/configuring.texy
- en/configuring.texy
According to: https://api.nette.org/2.4/source-Bridges.ApplicationDI.LatteExtension.php.html#22
> Configuring: added latte.templateClass

- cs/configuring.texy
- en/configuring.texy
> configuration: added showing session data in Tracy bar

- en/di-builtin-extensions.texy
Renamed "ConstantExtension" to "ConstantsExtension" and neon value "constant" to "constants"
> Fix constant names

- cs/form-validation.texy
https://ctrlv.cz/shots/2018/03/19/sMTm.png
But i am not sure this fixes the problem. Can i test is somehow before deploy?
> form-validation: hotfix missing column background

- cs/routing.texy
- en/routing.texy
> fix complete name %tld%

- tracy/cs/open-files-in-ide.texy
- tracy/en/open-files-in-ide.texy
> Tracy: fix .perex

- cs/composer.texy
- en/composer.texy
Please review @chemix, @paveljanda.
> Composer: install php@7.2 on macos

- cs/forms.texy
Method `Form::addProtection()` has only one parameter.
> fix info about first parameter in method Form::addProtection()

- en/bootstrap.texy
Revise the contents of the page discussing _Bootstrap_ in English. Correct grammar and improve formulations to make the text read more naturally.
> Correct grammar and formulation

- cs/configuring.texy
- en/configuring.texy
Pridal jsem nastrel routovani viz #677. Napada te @dg k tomu neco?
> Configuring: added routing example

- cs/configuring.texy
- en/configuring.texy
Please keep in mind that new version of http/application must be
released first.
> Configuring: mention CSP-Report-Only header

- cs/form-fields.texy
- en/form-fields.texy
Pridava, jiz jednou pridanou, ukazku na isSubmittedBy a isSubmitted.
> Forms: added example of isSubmittedBy and isSubmitted [#720]

- cs/localization.texy
- en/localization.texy
> Allow multiple parameters for translated messages

- pla/en/helper-loader.texy
http://bit.ly/2zBHVQH  
(line 68  is absolutely sufficient)
> This code does not work

- en/bootstrap.texy
> Fix neon address

- latte/en/macros.texy
Missing translation. For English speaker it is confusing name of variable.
> Latte: added missing translation

- en/quickstart/authentication.texy
Replacing Czech error message with English one.
> Quickstart: removed Czech error message

- cs/bootstrap.texy
- en/bootstrap.texy
according to https://github.com/nette/di/commit/40484ba713be9f898cb72f7cf01cf010a4612d0e
> External services: renamed external to imported

- cs/access-control.texy
- en/access-control.texy
Oprava návratové hodnoty v příkladu funkce authenticate().
> access-control -function authenticate(): Nette\Security\IIdentity

- cs/form-validation.texy
- en/form-validation.texy
Signed-off-by: Roman Ondráček <ondracek.roman@centrum.cz>
> Form Validation: fix the validation disabling example

- cs/di-extensions.texy
- en/di-extensions.texy
> Fixed DIC extension docs: loadDefinitions (deprecated) -> loadDefinitionsFromConfig

- cs/mailing.texy
I was searching for stuff about embedded images and I totally overlooked it when skimming the text.
> Improved heading structure (cs)

- en/mailing.texy
I was searching for stuff about embedded images and I totally overlooked it when skimming the text.
> Improved heading structure (en)

- cs/presenters.texy
Spelling corrected / Korektura koncovek
> Presenters edits

- cs/components.texy
- cs/presenters.texy
- cs/routing.texy
> Czech typo

- www/cs/contributing.texy
- www/en/contributing.texy
Hi,
at https://nette.org/cs/contributing#toc-coding-standards you have wrong/old parameters.
> contributing.texy - new coding standard parameters

- en/quickstart/getting-started.texy
Update command to really install web-project with nette version 2.4 instead v3
> Update composer command

- cs/presenters.texy
- en/presenters.texy
Problémové místo https://doc.nette.org/cs/3.0/presenters#toc-pouziti-modelovych-trid
1. public property není potřeba
2. samotná věta o public properties mi nedávala smysl, je to takto lepší?
> Injection in presenters

- cs/di-usage.texy
- en/di-usage.texy
https://forum.nette.org/cs/31860-vse-o-vydani-nette-3-0-prubezne-aktualizovano#p202669
> Remove caution about calling parent constructor in components

- cs/routing.texy
- en/routing.texy
Make it sense for you? I mean in routing basePath is not explained.
> routing: added explanation for variable 'basePath'

- cs/mailing.texy
- en/mailing.texy
As per [recurring mistake](https://forum.nette.org/cs/33236-kdyby-translation-chyba-pri-nacitani-latte-souboru) when using mailing, I'd like to propose this PR to
- add a mention about translate filter and other custom stuff added into latte
- tweak latte terminology
> mailing : adjust section regarding usage in Nette Application

- cs/floats.texy
- cs/utils.texy
- Documentation for `Nette\Utils\Floats`
> Added CZ docs for Nette\Utils\Floats

- en/application.texy
Small change switching a phrase in Czech to English (definitely not a direct/1:1 translation, but I figured the replacement text is nice and concise).
> Convert a phrase to English, in the English lang docs

- cs/quickstart/comments.texy
Found only in CS version. EN looks good.
> Corrected typo in table name

- latte/en/template-inheritance.texy
"it is very basic" sounds weird in my opinion, I was confused what it means.
> Improve text

- latte/en/template-inheritance.texy
Feel free to request explanations on particular things.
> Small improvements and fixes

- cs/arrays.texy
- en/arrays.texy
Až bude zaverzován https://github.com/nette/utils/commit/2f91d592b26a80d84bf9a50e880af3de750f1bc0
> utils: Arrays::wrap()

- tester/cs/helpers.texy
- tester/en/helpers.texy
> fixed namespace of purge

- latte/cs/syntax.texy
- latte/en/syntax.texy
> Added {block |filter} and {= 'x'|filter} into syntax docs

- cs/paginator.texy
- en/paginator.texy
- new feature? simple description of new methods, related to https://github.com/nette/utils/issues/262  
- BC break? no
> paginator: add getFirstItemOnPage & getLastItemOnPage methods

- tracy/cs/configuring.texy
- tracy/en/configuring.texy
Related PR: https://github.com/nette/tracy/pull/518
(plus couple more minor fixes)
> Tracy: Debugger::$scream

- doc/en/best-practices/@home.texy
> Forgotten translation to ENG

- latte/cs/tags.texy
- latte/en/tags.texy
- bug fix
- BC break? no
Fixing bad link
pls squash when merging, I edited it through github UI 👼🏻
> Strip filter is now spaceless

- doc/en/migrations/to-3-1.texy
- translate text
- BC break? no
> migrations: translate text

- latte/cs/tags.texy
- latte/en/tags.texy
- doc PR: 
- [https://latte.nette.org/cs/tags#toc-n-class](https://latte.nette.org/cs/tags#toc-n-class)
- [https://latte.nette.org/en/tags#toc-n-class](https://latte.nette.org/en/tags#toc-n-class)
> example of multiple class definition for n:class tag

- doc/cs/utils/images.texy
- bug fix? no
- new feature? no
- BC break? no
Just changed the title _obázku_ to _obrázku_
> Typo in documentation

- doc/en/dependency-injection/factory.texy
Hi,
I needed English documentation on Accessor and realized there isn't one (and that the Czech version was added only a few days ago) so I wrote it. This mirrors the Czech docs which was added with a WIP commit so I guess this is also a WIP version :-) Hope it will be useful anyway.
> Accessors EN docs

- cs/mail/@home.texy
- en/mail/@home.texy
> fixed creating Latte templates in mailing

- tracy/cs/recipes.texy
- tracy/en/recipes.texy
close #949
thx @dakujem ref: https://github.com/nette/tracy/pull/548
> Add custom scrubber in Tracy

- doc/en/application/bootstrap.texy
- doc/en/application/components.texy
- doc/en/caching/@home.texy
- doc/en/contributing/code.texy
- doc/en/contributing/coding-standard.texy
- doc/en/dependency-injection/configuration.texy
- doc/en/forms/rendering.texy
- doc/en/forms/standalone.texy
- doc/en/forms/validation.texy
- doc/en/mail/@home.texy
- doc/en/migrations/to-3-0.texy
- doc/en/php-generator/@home.texy
- doc/en/robot-loader.texy
- latte/cs/syntax.texy
- latte/en/syntax.texy
- bug fix / new feature?   Fixed spelling/grammar errors
- BC break? no
- doc PR: nette/docs
I found some spelling and grammar errors and fixed them :-)
> Fixed several typos and grammar errors

- doc/cs/http/configuration.texy
- doc/cs/http/sessions.texy
- doc/en/http/configuration.texy
- doc/en/http/sessions.texy
- There is no nette/http 3.1.3 version, correct is 3.1.5.
- Direct links to release.
> FIX: Reference to wrong nette/http version

- cs/forms/rendering.texy
- en/forms/rendering.texy
Add explanation how to use attributes with partial rendering.
> forms: add partial rendering & attributes remark

- best-practices/bg/dynamic-snippets.texy
- best-practices/cs/dynamic-snippets.texy
- best-practices/de/dynamic-snippets.texy
- best-practices/el/dynamic-snippets.texy
- best-practices/en/dynamic-snippets.texy
- best-practices/es/dynamic-snippets.texy
- best-practices/fr/dynamic-snippets.texy
- best-practices/hu/dynamic-snippets.texy
- best-practices/it/dynamic-snippets.texy
- best-practices/pl/dynamic-snippets.texy
- best-practices/pt/dynamic-snippets.texy
- best-practices/ro/dynamic-snippets.texy
- best-practices/ru/dynamic-snippets.texy
- best-practices/sl/dynamic-snippets.texy
- best-practices/tr/dynamic-snippets.texy
- best-practices/uk/dynamic-snippets.texy
- bug fix / new feature?
- BC break? yes/no
- doc PR: nette/docs#???
> Fix Unsupported operand types: string - int

- dependency-injection/de/faq.texy
- bug fix? yes
- new feature? no
- BC break? no
fixed an incorrect sentence
> update german version of faq.texy

- forms/cs/rendering.texy
I propose to make clear already in the first paragraph in introduction that there are basically two ways of rendering forms - without template and with template.
> More precise specification in the introduction

- forms/cs/rendering.texy
Hi, although this point is not so important, understandable headings are important for quick orientation in the text.
> More understandable section headings

- latte/cs/template-inheritance.texy
Hi, just more clear formulation
> More clear formulation

- latte/cs/tags.texy
Just make the point more clear
> More clear formulation 2

- application/cs/presenters.texy
Hi, just small improvement - better explanation od http response codes of redirect presenter methods
> specification of redirect presenter methods

- database/cs/explorer.texy
I have compared the not very clear czech paragraph  with the english version:
"If you want to fetch multiple books, you should use the same approach. Nette Database Explorer will fetch authors and translators for all the fetched books at once."
and completed the czech version according to the clear meaning of english version.
> Completing missing word

- dependency-injection/cs/container.texy
- bug fix
- BC break? no
- doc PR: nette/docs#???
> Typo in container.texy

- forms/cs/validation.texy
- migrations/cs/@home.texy
- migrations/cs/@left-menu.texy
- migrations/cs/to-4-0.texy
- migrations/en/@home.texy
- migrations/en/@left-menu.texy
- migrations/en/to-4-0.texy
I had to google explanation in which units the MaxFileSize validation filter is so I added it to the documentation directly.
> Forms validation - MaxFileSize is in bytes

- forms/cs/validation.texy
> Fixed typo
