- cs/@docmenu.texy
- cs/testing-with-travis.texy
- en/@docmenu.texy
- en/testing-with-travis.texy
Added new section about running tester with Travis CI.
This is just a draft, feedback needed.
After the draft is approved, I will translate the article in English and then squash all the commits.
ref https://github.com/nette/tester/issues/189
> Tester: added new section about running Tester with Travis CI

- cs/homepage.texy
- en/homepage.texy
Looks like I've forgotten to add links for Debugger extensions and CI to the `homepage`.
> Homepage: added reference to CI and Debugger extensions

- cs/default-macros.texy
- cs/presenters.texy
- en/default-macros.texy
- en/presenters.texy
According to @dg['s suggestion](http://forum.nette.org/cs/17100-co-vylepsit-na-dokumentaci), macro {ifCurrent} needs moving from `conditions` to `links` section.
I'm not 100% sure this is right. I would like to hear your opinions on this, thanks in advance :)
EDIT: I will fix the EN version when we agree on a solution.
> IfCurrent: moved from conditions to links

- cs/localization.texy
- en/localization.texy
If you believe there are more ITranslator implementations that should be linked, please tell me.
> Localization: added warning about no default translator

- cs/dependency-injection.texy
- en/dependency-injection.texy
"Deprecated: Nette\DI\Container::__get() is deprecated; use getService()
or enable di.accessors in configuration."
Less magic, less confusion :thumbsup:
> Do not use deprecated code in DI examples

- cs/ajax.texy
- en/ajax.texy
> Ajax: Remove broken link to fifteen example

- cs/default-macros.texy
- en/default-macros.texy
I shoot my self in a foot trying to do `{syntax off}{$x}{/syntax}` while presenting Latte in work.
> Removed closing {/syntax} from macros preview

- cs/quickstart/authentication.texy
- en/quickstart/authentication.texy
Due to https://github.com/nette/nette/issues/1526 - it is not clearly that which namespace I have to use
> typo fix in form class - due to 1526

- en/presenters.texy
I really like the Nette framework, and it is nicely documented. However, since I do not speak czech, I have to rely on the english documentation which is at times - shall we say - a bit clumsy. I have taken the opportunity to improve parts of it, and remove some small spelling mistakes alongside.
For starters I thought it best to attack a single page first and see how the review process goes.
Note that, since I do not speak czech, I rely on the english present and simply revise and rewrite.
> en/presenters: fix clunky english, fix spelling errors. No content changes

- cs/localization.texy
- en/localization.texy
Hi,
I just marked [sakren/nette-translator](https://github.com/davidkudera/nette-translator) as abandoned package, so it should be removed also from documentation.
There was a discussion at nette/web-content#179 about translators which should be added here. I'm really grateful that my package was chosen, even when I know that it was mainly because otherwise this list would look biased... 
So I'll ask you for the same thing like in that previous pull request:
"If you believe there are more ITranslator implementations that should be linked, please tell me."
> Localization: removed link to abandoned sakren/translator

- cs/access-control.texy
- en/access-control.texy
`Nette\Security\User` doesn't have `setNamespace` method.
> Fix in example "how to set namespace for user storage"

- cs/routing.texy
- en/routing.texy
Route::$defaultFlags is deprecated, so there is substitude for it.
> Added substitude for $defaultFlags

- cs/routing.texy
- en/routing.texy
Fix Use-statment to newer coding standard in examples
Updated last example "Custom router" in CS translation to match newer version from EN translation in en/routing.texy
> cs/routing.texy, en/routing.texy fix to match examples

- latte/cs/macros.texy
- latte/en/macros.texy
Currently when you open Latte documentation page for [Default Latte Macros](https://latte.nette.org/en/macros) it is not possible go from links in table with macros to the selected content below the table. This pull request fixes that in Czech and English version of documentation.
> Latte: links in default macros

- latte/cs/macros.texy
- latte/en/macros.texy
Macro {includeblock} is [depreciated](https://forum.nette.org/cs/26250-pojdte-otestovat-nette-2-4-rc). Maybe it will be better have in documentation macro {import} instead that.
> Latte: include block depreciation

- tracy/cs/homepage.texy
- tracy/en/homepage.texy
Required since https://github.com/nette/tracy/commit/13f854d4c11221add4697121e183a147732bb13b
Content Security Policy nonce (see https://github.com/nette/tracy/issues/136) is the future but now this doc update should do.
Thanks!
> Tracy requires 'self' in CSP since 2.4

- tester/cs/homepage.texy
- tester/en/homepage.texy
see `\Tester\Runner\Runner::$outputHandlers`
> Tester: fix typo in --setup option (outputHandlers)

- cs/configuring.texy
I am sorry I didn't notice this misspell before...
See related commit dce61b8
> Fix typo in custom macro registration text (cs)

- cs/components.texy
From the original description it wasn't obvious that the render method gets the parameters, not the Presenter method.
> clarification of passing arguments to render()

- cs/routing.texy
- en/routing.texy
Rewrite rule flags use comma as separator, cannot be used space.
With spaces, server throw error 500.
`!= on` can be simplified as `off`
`^(.*)$` can be simplified as `.*`
> Repaired rewrite rule flags

- en/configuring.texy
According to commit https://github.com/nette/di/commit/eba68180013a5f9d81ce892984dca758c178be57 accessors options was removed in Nette 2.4 so it should not be mentioned in documentation.
> Removed missing config option in 2.4.

- tracy/cs/extensions.texy
- tracy/en/extensions.texy
CSS classes - replace .nette- prefix with .tracy-
attribues - use 'href' instead of 'rel'
> tracy-extensions: correct CSS classes and attributes

- latte/cs/macros.texy
- latte/en/macros.texy
Ještě chybí `{snippetArea}`, ale tam nevím, jak to zkráceně popsat :o)
> Doplnění core maker

- www/en/coding-standard.texy
Probably not the case anymore, since Smart traits came and "Object" is a keyword
> coding-standard: drop Nette\Object ancesstor for all

- www/en/coding-standard.texy
> Typo: trailing ```

- cs/configuring.texy
- en/configuring.texy
Opravil jsem spatne vygenerovane odkazy, resp. toc.
> Configuration: repair headlines, add some code examples

- cs/homepage.texy
- cs/random.texy
- cs/strings.texy
- en/homepage.texy
- en/random.texy
- en/strings.texy
This PR removes deprecated [`Strings::random()`](https://api.nette.org/2.4/source-Utils.Strings.php.html#418-426)
> String: remove deprecated random() method

- en/ajax.texy
The purpose of these docs is probably more about helping the reader *use* the framework than about helping them understand how exactly it works internally or what was the reasoning behind the internal workings ("Therefore it is not possible to call some render method of every invalid object"). The removed paragraph serves no purpose other than to add noise to something the following paragraph explains in the first sentence ("Rendering of the page proceeds very similarly as in case of a regular request") and expand on what are snippets (which is a term that has been used previously and should therefore have been explained previously).
> Removed an excessive explanation

- latte/en/homepage.texy
I added the missing brackets that were missing in the EN version. In the Czech version, the code was correct.
> Fix EN code example in "Template from string"

- cs/form-validation.texy
- en/form-validation.texy
I tested it at https://editor.nette.org/, but there `api` helper don't generate domain to `https://api.nette.org/2.4/` but path should be good.
> Form validation: Fix link to error messages of validation rules

- cs/di-configuration.texy
- en/di-configuration.texy
Fix little mistage between example `.neon` code and generated PHP code.
> di-configuration: Fix typo in example code

- cs/di-extensions.texy
beforeCompile(), fix syntax error in example.
> Example method beforeCompile(), fix syntax error.

- cs/form-fields.texy
- en/form-fields.texy
Hey!
A little late, but still :-)
This documents nette/forms#186 and nette/forms#187.
A couple of things:
1. Should I add something like `since nette/forms > 2.4.8 or dev-master as of YYYY-MM-DD`?
2. Once we agree on this, I'll make a Czech translation.
Thanks!
> Forms: add notes about Form::PATTERN_ICASE

- cs/presenters.texy
- en/presenters.texy
Ukazky pro:
- use Nette\Application\Responses\TextResponse;
- use Nette\Application\Responses\RedirectResponse;
- use Nette\Application\Responses\JsonResponse;
- use Nette\Application\Responses\FileResponse;
- use Nette\Application\Responses\CallbackResponse;
- use Nette\Application\Responses\ForwardResponse;
> Presenters: more examples of send<> methods [#670]

- cs/configuring.texy
- en/configuring.texy
There is a broken link to "Invalid links" section.
The same is in the documentation for the version 3.0, but I don't know what is the best way to fix it there too. Open another pull request?
> Configuring: Fix link to the "Invalid links" section

- en/database-core.texy
the current docs show that you can pass each row to be inserted as additional params to the query method, however when you try to do that it errors.  In looking up this error here: https://forum.nette.org/en/21412-nette-database-insert-multiple-rows-in-one-query I realized that the multiple rows need to be passed as an array in the second argument which solved the problem.
> Fixed a documentation error regarding Multiple insert

- en/form-fields.texy
I think this constructor isn't needed. In all other code examples there is no constructor, so I don't see reason for having constructor here.
> Form Fields: removed unnecessary constructor

- en/configuring.texy
Removed typo. I think it's the skipped translation from Czech to English.
> Configuration: removed typo.

- en/database-core.texy
I think it's misstake from copying Czech text and translating it into English.
> Database: removed Czech word from English text

- tester/en/writing-tests.texy
Checkout code of Nette Tester: https://github.com/nette/tester/blob/master/src/Framework/Assert.php.
Method header is:
`public static function exception(callable $function, string $class, string $message = null, $code = null): ?\Throwable`.
In description of method features there is `$code` parameter mentioned but it is missing in the documentation method header.
> Tester: fixed exception method description

- en/strings.texy
I think it is better to keep English documentation in English even in this code example.
> Strings: removed Czech word from English documentation

- en/database-explorer.texy
Hello David, maintainers.
I'm not sure you welcome partial updates, but I have to say I may not have time or enthusiasm to go over the docs as a whole, so I'm providing this ... (and hopefuly more will come in the future, if you are interested)
I believe the English version of the documentation is not up to the quality of the code of the framework itself, which may degrade the framework in the eyes of foreign viewers. That is why I decided to to give a hand here. And the database explorer was the part of the docs I (literally) stumbled upon first.
---
Also, I would advise to use the passive voice when possible, as in technical English it is preferred to "we can" / "you can". I'm not sure to what extent I'm allowed to reformulate stuff.
> Wording & grammar fixes, part 1

- en/quickstart/creating-posts.texy
Fix error "Argument 1 passed to Nette\Database\Table\ActiveRow::update() must be iterable, object given". Or stdClass type arguments of commentFormSucceeded() and postFormSucceeded() functions could be replaced with ArrayObject types.
> Cast stdClass to iterable array

- cs/quickstart/getting-started.texy
- en/quickstart/getting-started.texy
This commit completes the SELinux section in both cs and en quickstart.
> Quickstart: complete the SELinux note on Linux systems

- tracy/cs/guide.texy
- tracy/en/guide.texy
Firelogger již není dostupný pro Firefox
> removed FireLogger in Firefox, plugin is not available yet

- cs/configuring.texy
Confusing tab spaces / indentation in documentation sometimes should make you think that there is missing 'parent' node
Better to take a look at real doc. at https://doc.nette.org/cs/3.0/configuring
> Confusing tab spaces

- cs/link-generation.texy
- en/link-generation.texy
b8084e31ba39cde7f881977ee2299f662262ef47 has broken Latte doc. Link explaining ifCurrent tag in [Links](https://latte.nette.org/en/tags#toc-available-only-in-nette-framework) section does not exist. To be exact, concrete anchor does not exist.
ifCurrent tag is marked as deprecated in Latte documentation, so I've replaced it with it's $presenter->isLinkCurrent() equivalent.
The only thing that must be done is to fix link in Latte doc - I've no clue where to send PR...
> Create link target for Latte documentation, fix incomatibility with Latte description

- cs/link-generation.texy
- en/link-generation.texy
Adds `isModuleCurrent()` description into link generation section.
I've mentioned modular application/modules, but I haven't found any module related part in documentation. I've linked module usage example from nette/examples repository. In case I've missed description in documentation, let me know, I'm gonna fix it.
I'm not sure if there's any way how to sync this PR with nette/application release as this method is currently in master only...
> mention isModuleCurrent() method

- tester/cs/testing-with-travis.texy
Česká stránka https://tester.nette.org/cs/testing-with-travis
Informace o odstranění podpory na https://github.com/nette/tester/releases/tag/v2.0.0
Nechal jsem tam HHVM informace, protože je zde dobře a česky vysvětleno nastavení Travisu a násobení nastavení při spouštění.
> tester: removed support for HHVM

- cs/configuring.texy
- cs/mailing.texy
- en/configuring.texy
- en/mailing.texy
`testMode` proměnná je tam pouze pro automatické testy a rozhodně bych ji nedokumentoval. Pošlu pak PR pro jeho odstraní ze samotného podepisovače, protože se to dá udělat lépe.
> DKIM testMode

- cs/configuring.texy
- en/configuring.texy
In Nette 2.4 `cookieSamesite` configuration parameter is implemented as of <https://forum.nette.org/cs/31207-podpora-samesite-cookie-v-nette-a-csrf>. But it is missing in documentation,
> Configuring: samesite cookies in 2.4

- cs/translations.texy
- en/translations.texy
`translate` macro is not working for strings without `=`.
> fix using tranlation filter in latte

- cs/bootstrap.texy
- en/bootstrap.texy
Came up because of this issue: https://github.com/docker-library/php/issues/74
In the end, the "suggested" `php.ini` config is:
```ini
; Default Value: "EGPCS"
; Development Value: "GPCS"
; Production Value: "GPCS";
; http://php.net/variables-order
variables_order = "GPCS"
```
Therefore the `$_ENV` variable is not populated.
> Using `getenv` instead of `$_ENV`

- cs/quickstart/authentication.texy
- cs/quickstart/comments.texy
- en/quickstart/authentication.texy
Initially, my ambition was to add "common.neon" reference to the sentence since it took me a while (as a newbie following this guideline) to realize where to paste the _security_ section. Just a while ago, I noticed the file reference gets displayed when hovering my mouse over the textbox. 
So my contribution reduced to "polishing" the Czech sentence only and amending the English one accordingly.
Please consider if the NEON file reference should be mentioned in the text, or it's redundant in your opinion.
I'd be happy to update it :)
> Sentence polishing

- cs/configuring.texy
- en/configuring.texy
Hello, 
after testing tracy 2.8 RC I found that key for theme should be 'dumpTheme' instead of 'theme' (https://github.com/nette/tracy/blob/v2.8.0-RC/src/Bridges/Nette/TracyExtension.php#L49)
> Configuration: fix tracy theme key

- cs/access-control.texy
- **Role** used `admin`
- **Authorizator** used `admin`
- **Permission ACL** used `administrator`
> Unify role naming across sections

- en/configuring.texy
This fixes a few broken links.
I wonder if we should not have some broken link checker running in CI.
> configuring: Sync intro links with heading texts

- latte/en/sandbox.texy
there were some words left from previous version or something
> Fix typo in sandbox docs

- en/passwords.texy
The Passwords class is part of nette/security, not nette/utils
> fix: incorrect package in passwords

- doc/cs/dependency-injection/extensions.texy
- doc/en/dependency-injection/extensions.texy
Fix for extensions.texy - the foreach was missing the `$key` part and using the `$value` as such.
> Fix findByTag foreach

- doc/cs/http/request.texy
- doc/en/http/request.texy
This adds documentation for nette/http#207 / nette/http#212
> Document directory upload support

- doc/cs/utils/type.texy
- doc/en/utils/type.texy
correct method name (https://github.com/nette/utils/blob/master/src/Utils/Type.php#L213)
`allow()` -> `allows()`
> typography 

- tracy/cs/guide.texy
Hi, I propose to complete into documentation cookie name "nette-debug" for establishing secure development mode, because it is missing. In the documentation there is only mentioned "tracy-debug" for Tracy out of Nette. Iam sending alltogether 20 pullrequests for every language version one ;)
> Doplnění názvu cookie nette-debug pro verzi s Nette

- tracy/cs/guide.texy
A complete Tracy novice will easily miss the mention of the require 'vendor/autoload.php' line, which is hidden in a block of text in the current version of the documentation, while it is a mandatory line for proper activation of Tracy.
> Adding a line to the Tracy activation code sample

- forms/cs/rendering.texy
Hi, the sample code of rendered html by default form renderer doesn't match the reality of how the renderer actually renders the html. So I propose to add the attribute required of input element.
> Complete sample code - add attribute required

- application/cs/ajax.texy
Hi,
I send a proposal to complete info about the http ajax request. The introduction paragraph talks about an ajax http request on the server, but newcomers need a brief input on how an ajax request is actually created - that's what the paragraph should ideally start with. It is also appropriate to give an Ajax request as such a separate title.
> Add info - creating ajax request in the browser

- forms/cs/rendering.texy
Latte tag {form}{/form} is insufficiently described in the documentation. The tag is mentioned in Latte https://latte.nette.org/cs/tags, in the paragraph "Only available with Nette Forms". Here is just a link that leads to the Nette Forms documentation: https://doc.nette.org/cs/forms/rendering#toc-latte, but again we can't find any definition of this tag.
Since the tag {form "formName"}{/form} is essentially an alternative notation for <form n:name="formName" ...>, which is well described in the documentation, I suggest inserting only a small separate paragraph where it would be clearly explained .
+ change correspondingly the link from documentation Latte
> Minimal description of tag {form}{/form}

- application/cs/templates.texy
Hi, presenter actually searches more files as templates than written in the documentation - see: https://github.com/nette/application/blob/master/src/Application/UI/Presenter.php#L514
First he searches files in /template directory insight directory with presenter class. After that he searches files in /template directory one level higher e.g. at the same level as directory with presenter class. This is very useful feature and many developers use this.
I propose to complete the description of the searching template files in the documentation.
> Finding template file - complete description of function

- application/cs/bootstrap.texy
Hi, information about default static parameters is important. It should be prominently listed with its own title in both the Configuration section and the Bootstrap section, as it is related to both topics. I send 2 PRs to each section separately.
> Default static parameters - addition

- database/en/explorer.texy
In Czech version is this text:  "Metoda insert() přijímá pole nebo Traversable objekty" so I have changed the english translation accordingly
> Correct english translation

- http/cs/request.texy
- http/en/request.texy
- new feature?
- BC break? no
Added AVIF image support for Http FileUpload
> AVIF image FileUpload support

- forms/cs/configuration.texy
- forms/cs/controls.texy
- forms/cs/validation.texy
- forms/en/configuration.texy
- forms/en/controls.texy
- forms/en/validation.texy
- new feature? yes
- BC break? no
Added AVIF image support for Forms.
Added ability to chain multiple MimeType validators  together and prevent deletion of previously set rules.
> AVIF image Forms support and MimeType chaining

- latte/en/syntax.texy
Fix typo of `atribut` to `attribute`
- Typo Fix
- BC break: no
- Doc PR: nette/docs
> Fix typo in syntax.texy

- tester/en/running-tests.texy
- ***new feature*** https://github.com/nette/tester/pull/443
> Added docs for new "console-lines" output mode

- latte/en/template-inheritance.texy
Some English grammar corrections that make the documentation a little easier to understand and sound more professional.
Just trying to help make things better as I'm reading!
- bug fix / new feature?   no
- BC break? no
- doc PR: nette/docs#???  yes, just English corrections
> Grammar corrected in documentation

- dependency-injection/de/container.texy
Fixes the german translation for the dependency injection container documentation. This probably was an oversight when translating to german. 
Not a breaking change and no issue to be assigned.
> fix german di container translation
